### ISSUE TITLE
Support for custom Clair3 models?

### ISSUE THREAD

**Issue by peterk87** [OLF-Bioinformatics/VariantDetective#3]
There are a lot of models available at [Rerio](https://github.com/nanoporetech/rerio) that might be more suitable for ONT data generated on the newer R10 flowcells.

https://github.com/nanoporetech/rerio#clair3-models

Is there support in VD for specifying custom models?

**Comment by philcharron-cfia** [comment]
Thanks for the suggestion @peterk87. I have added a parameter called "--custom_clair3_model" to both "snp_indel' and "all_variants". This allows the user to specify the path where a custom Clair3 model can be found. If the parameter isn't called, it simply uses the default model file.
