### ISSUE TITLE
Remove Clair3 models from repo?

### ISSUE THREAD

**Issue by peterk87** [OLF-Bioinformatics/VariantDetective#4]
It might not be necessary to include the Clair3 models with VD when Clair3 already comes with them when its installed via Bioconda or Docker/Singularity since various models are included by default. They might be present in different locations depending on if you're using the Bioconda version or Docker/Singularity version (see [nf-flu clair3 process def](https://github.com/CFIA-NCFAD/nf-flu/blob/c61789e577401f74cd61c9da88554c3163d2d5ff/modules/local/clair3.nf#L35)). 

The Clair3 models in this repo are quite large and may make it challenging to add VD to PyPI.

**Comment by philcharron-cfia** [comment]
Thanks for the suggestion @peterk87. I have fixed the Clair3 command to use the Clair3 models that are supplied during conda install and have removed them from the VD repo.
